### ISSUE TITLE
Escher breaks with an url encoded plus sign

### ISSUE THREAD

**Issue by mruell** [emartech/escher-php#17]
I have the issue, that I need to make an RD request like:

rds/connections/CONNECTION/tables/TABLE/records?email=test%2Bbayxd%40gmail.com

So I'm selecting by email and that email is `test+bayxd@gmail.com`, so urlencoded its `test%2Bbayxd%40gmail.com`

This leads to an error at this point in the code:
https://github.com/emartech/escher-php/blob/7c635742f8168c0c37a84e74031a6d0d0215ddd9/src/Escher/RequestCanonicalizer.php#L40-L45

First in L40/41 the values/keys are decoded, from their original state. So `test%2Bbayxd%40gmail.com` becomes `test+bayxd@gmail.com`, then the plus is replaced with a space and reencoded.

So now the value is `test bayxd@gmail.com` which is wrong!
This leads to me beeing unable to make the RD request above.

I guess the reason is, that a plus refers to a space in urlencoded strings, but since it was decoded the str_replace does not make sense here.

**Comment by deugeniu** [comment]
This behaviour is fixed in version 3.0.0
