### ISSUE TITLE
Unindexed arrays in query strings does not work

### ISSUE THREAD

**Issue by zkiiito** [emartech/escher-php#8]
Escher uses the parse_str function to parse query params for stripping auth parameters.
if I have unindexed arrays in the query, parse_str converts them to indexed ones, calls http_build_query and the signatures do not match:

parse_str('id[]=1&id[]=2', $params);
var_dump(http_build_query($params));

I'd suggest reimplementing the stripAuthParams function.

**Comment by szeist** [comment]
Hi zkiiito,

Thanks for reporting!
We fixed this issue in release 0.2.13.

All the best,
Istvan
